Update code.yml

diff --git a/.github/workflows/code.yml b/.github/workflows/code.yml
--- a/.github/workflows/code.yml
+++ b/.github/workflows/code.yml
@@ -2,54 +2,54 @@ name: VPN Test
 
 on: [push]
 
-jobs:
-  test-vpn:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Install OpenVPN
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y openvpn
-          
-      - name: Connect to VPN
-        run: |
-          pwd && ls -la
-          echo "${{ secrets.OPENVPN_CONFIG }}" | base64 --decode > github-runner.ovpn
-          pwd && ls -la
-          cat github-runner.ovpn
-          sudo modprobe tun
-          sudo openvpn --config github-runner.ovpn 
-
-
-      - name: Check VPN Connection
-        run: |
-          # Check the IP address to verify the VPN connection
-          ip addr show tun0 || echo "VPN not connected"
-          # Optionally check public IP
-          curl ifconfig.me || echo "Failed to get public IP"
-
-      - name: Run your job
-        run: |
-          echo "Running tasks over VPN..."
-
 # jobs:
-#   deploy:
-#     runs-on: self-hosted  
+#   test-vpn:
+#     runs-on: ubuntu-latest
 #     steps:
-#       - name: Checkout code
-#         uses: actions/checkout@v4
-        
-#       - uses: actions-hub/kubectl@master
-#         env:
-#           KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
-#         with:
-#           args: get pods
-#       - name: checking manifest files
-#         run: pwd && ls -la
-#       - name: k8s
+#       - name: Install OpenVPN
 #         run: |
-#              kubectl apply -f namespace.yaml
-#              kubectl apply -f configmap.yaml
-#              kubectl apply -f deployment.yaml
-#              kubectl apply -f service.yaml
+#           sudo apt-get update
+#           sudo apt-get install -y openvpn
+          
+#       - name: Connect to VPN
+#         run: |
+#           pwd && ls -la
+#           echo "${{ secrets.OPENVPN_CONFIG }}" | base64 --decode > github-runner.ovpn
+#           pwd && ls -la
+#           cat github-runner.ovpn
+#           sudo modprobe tun
+#           sudo openvpn --config github-runner.ovpn 
+
+
+#       - name: Check VPN Connection
+#         run: |
+#           # Check the IP address to verify the VPN connection
+#           ip addr show tun0 || echo "VPN not connected"
+#           # Optionally check public IP
+#           curl ifconfig.me || echo "Failed to get public IP"
+
+#       - name: Run your job
+#         run: |
+#           echo "Running tasks over VPN..."
+
+jobs:
+  deploy:
+    runs-on: self-hosted  
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        
+      - uses: actions-hub/kubectl@master
+        env:
+          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
+        with:
+          args: get pods
+      - name: checking manifest files
+        run: pwd && ls -la
+      - name: k8s
+        run: |
+             kubectl apply -f namespace.yaml
+             kubectl apply -f configmap.yaml
+             kubectl apply -f deployment.yaml
+             kubectl apply -f service.yaml
 
